apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 80         # 외부에 노출될 포트
      targetPort: 8080 # 컨테이너의 포트
      nodePort: 30080  # 외부에서 접근할 포트
  type: NodePort
